server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomm_demo
    username: postgres
    password: qwerty1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  jwt:
    secret: "this-is-a-very-long-random-secret-key-32bytes-minimum!!!"
    ttlSeconds: 3600

stripe:
  secret-key: ${STRIPE_SECRET_KEY}

